name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  buildtest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./06_artifactsoutputs
    steps:
      - name: Get code
        uses: actions/checkout@v3.5.2
      - name: "Install Node JS"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Build website
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dist-files
          path: |
            ./06_artifactsoutputs/dist  
  deploy:
    needs: buildtest
    runs-on: ubuntu-latest
    steps:
      - name: "Install Node JS"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get build artifacts
        uses: actions/download-artifact@v3.0.2
        with:
          name: dist-files
      - name: output contents
        run: ls -R
      - name: Deploy
        run: echo "Deploying..."
