name: Test And Deploy Project
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./02_project
    steps:
        - name: "Get Code"
          uses: actions/checkout@v3.5.2
        - name: "Install Node JS"
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: "Install Dependencies"
          run: npm ci
        - name: "Run Tests"
          run: npm test
        - name: "Some Debugging Info"
          run: |
            echo "Hello World"
            echo "The event name is ${{ github.event_name }}"
            echo "The ref is ${{ github.ref }}"
            echo "The sha is ${{ github.sha }}"
            echo "The workflow is ${{ github.workflow }}"
            echo "The action is ${{ github.action }}"
            echo "The actor is ${{ github.actor }}"
            echo "The repository is ${{ github.repository }}"
            echo "The event path is ${{ github.event_path }}"
            echo "The workspace is ${{ github.workspace }}"
            echo "The head ref is ${{ github.head_ref }}"
            echo "The base ref is ${{ github.base_ref }}"
            echo "The server url is ${{ github.server_url }}"
            echo "The api url is ${{ github.api_url }}"
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./02_project
    steps:
        - name: "Get Code"
          uses: actions/checkout@v3.5.2
        - name: "Install Node JS"
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: "Install Dependencies"
          run: npm ci
        - name: "Build project"
          run: npm run build
        - name: "Deploy"
          run: echo "Deploying..."
