name: container-deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: node:18
    defaults:
      run:
        working-directory: ./09_containers
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Output information
        run: |
          echo "testing..."
  deploy:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |
          echo "deploying..."
          echo "PORT: $PORT"