name: container-deployment
on:
  push:
    branches:
      - main
env:
  CACHE_KEY: node-deps
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: node:18
    services:
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    defaults:
      run:
        working-directory: ./09_containers
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.node_modules
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: connect to redis
        run: node client.js
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379