name: linttestdeploy
on: [push]
jobs:
  lintbuildtest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./04_practice
    steps:
        - name: "Get Code"
          uses: actions/checkout@v3.5.2
        - name: "Install Node JS"
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: "Install Dependencies"
          run: npm ci
        - name: "Lint"
          run: npm run lint
        - name: "test"
          run: npm run test
        - name: "build"
          run: npm run build

