name: matrix demo
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [16, 18]
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: ./08_execution_flow
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
